let suggestions =[
    "Amazon FBA Specialist",
    "Amazon Seller Central Consultant",
   "Administrative Assistant",
    "Arts Freelancer",
    "Adobe After Effects Specialist",
   "Adobe InDesign Expert",
    "Anime Freelancer",
    "Adobe Premiere Pro Specialist",
    "Animator",
    "Album Cover Designer",
    "Actor",
    "Adobe Illustrator Expert",
    "Adobe Acrobat Expert",
    "Adobe Photoshop Expert",
    "Adobe Photoshop Lightroom Specialist",
    "Audio Production Specialist",
    "Acrylic Painter",
    "Audio Editor",
    "Book Designer",
"Business Presentation Freelancer",
"Brochure Designer",
"Branding Freelancer",
"Blender3D Specialist",
"Book Cover Designer",
"Blockchain Developer",
"Babylon.js Freelancer",
"BigQuery Developer",
"Dropshipper",
"Data Entry Specialist",
"Data Scraper",
"Digital Artist",
"Desktop Publishing Specialist",
"Drawer",
"Digital Design Freelancer",
"Database Design and Construction Freelancer",
"Django Freelancer",
"Data Extraction Specialist",
"Data Visualization Specialist",
"Database Designer",
"Data Miner",
"Deep Learning Expert",
"Data Analyst",
"Data Scientist",
"d3.js Developer",
"DevOps Engineer",
"Docker Specialist",
"Delphi Developer",
"Data Cleansing Analyst",
"Data analytics Freelancer",
"Digital Marketer",
"Drafting Specialist",
"Digital Signal Processing Specialist",
"Dietitian",
"Excel Freelancer",
"eBay Listing Writer",
"Error Detection Freelancer",
"Email Handler",
"Etsy Administration Specialist",
"Excel Expert",
"ePub Specialist",
"ESP32 Freelancer",
"Elementor Freelancer",
"ERPNext Specialist",
"Erlang Developers & Programmer",
"Employment Law Lawyers & Legal Professional",
"Event Planner",
"Electronics Specialist",
"Engineering Drawing Specialist",
"Electrical Drawing Specialist",
"Estimating Freelancer",
"Electrical Engineer",
"Estimator Specialist",
"English - India Freelancer",
"Estonian Freelancer",
"English to Dutch Translator",
"English to Italian Translator",
"Essay Writer",
"English to Portuguese Translator",
"English to Korean Translator",
"English to Spanish Translator",
"Ebook Writer",
"English Proofreader",
"English to Malay Translator",
"English to Polish Translator",
"Editor",
"English to Arabic Translator",
"Fashion Designer",
"Fashion Illustrator",
"Flyer Designer",
"FFmpeg Specialist",
"Forex Trader",
"Guitar Family Freelancer",
"GIF Freelancer",
"Graphic Designer",
"Genesis Framework Freelancer",
"Google Apps Script Freelancer",
"Google Sheets Freelancer",
"Game Designer",
"Geographic Information System (GIS) Developer",
"Google Cloud Platform Developer",
"Google Data Studio Specialist",
"Google AdWords Expert",
"Google Analytics Expert",
"German - Germany Freelancer",
"Grammar Freelancer",
"Ghostwriter",
"German Specialist",
"Grant Writer",
"HTML Developer",
"Haskell Developers & Programmer",
"HubSpot Specialist",
"iCD Coding Specialist",
"Illustrator",
"Image/Object Recognition Freelancer",
"iOS Developer",
"Jewelry Designer",
"JavaScript Developer",
"Job Description Writer",
"Japanese Translators & Writer",
"Kindle Direct Publishing Freelancer",
"Korean to English Translator",
"Korean Translators & Writer",
"Logo Freelancer",
"Logo Designer",
"Lyrics Video Freelancer",
"Logo Animation Freelancer",
"Linux Developer",
"Microsoft Project Specialist",
"Medical Freelancer",
"Microsoft Word Expert",
"Medical Coders, Biller",
"Medical Transcriptionist",
"Marketing Presentation Freelancer",
"Male Voice Over Artist",
"Music Producer",
"Musical Composition Specialist",
"Medical Illustrator",
"Mobile App Design Freelancer",
"Microsoft Excel PowerPivot Specialist",
"Microsoft Power BI Specialist",
"Mobile App Developer",
"Narrator",
"NopCommerce Developer",
"Non-Fiction Writer",
"Oberlo Freelancer",
"OCR Tesseract Specialist",
"Ontologist",
"Pages Specialist",
"PDF Converter",
"Project Manager",
"PowerPoint Expert",
"Podcasting Specialist",
"Quality Control Freelancer",
"Qt Developer",
"QuickBooks Consultant",
"Real Estate Freelancer",
"Reaper Freelancer",
"Resume Design Freelancer",
"Ruby on Rails Developer",
"Survey Freelancer",
"Spreadsheets Specialist",
"Scriptwriting Freelancer",
"Social Media Design Freelancer",
"Storyboard Freelancer",
"Signage Freelancer",
"Sewing Freelancer",
"Singer",
"Spine Freelancer",
"Sharepoint Freelancer",
"Salesforce Lightning Freelancer",
"Task Coordination Freelancer",
"Technical Support Specialist",
"Transcriptionist",
"Time Management Specialist",
"Typesetter",
"Unity3D Freelancer",
"UX Designer",
"UI Designer",
"Unity Developer",
"Ukrainian Translators & Writer",
"Virtual Freelancer",
"Virtual Assistant",
"Visual Design Freelancer",
"Video Editor",
"Videographer",
"Vector Art Freelancer",
"Voice Acting Freelancer",
"Voice Over American Accent Specialist",
"Vector Illustration Freelancer",
"VFX Animation Specialist",
"Voice Over Actor",
"Voice Talent",
"Vector Tracing Freelancer",
"Whiteboard Animator",
"Website Freelancer",
"WordPress Developer",
"Website redesign Freelancer",
"Windows PowerShell Developer",
"Web Designer",
"WebGL Developer",
"Woocommerce Developer",
"Wordpress Theme Freelancer",
"Webflow Developer",
"WebRTC Developer",
"Web Scraper",
"Website Developer",
"Web Testing Specialist",
"Web Application Freelancer",
"Web Crawler Develope",
"Xamarin Specialist",
"Xero Specialist",
"Xactimate Specialist",
"YouTube Freelancer",
"YouTube API Developer",
"Zoom Video Conferencing Specialist",
"Zapier Developer",
];